-- Supabase Dashboard → SQL Editor에서 이 파일 전체를 실행하세요.
-- 기존 점수는 유지하면서 고유 닉네임과 플레이어별 최고 점수 뷰를 추가합니다.

create table if not exists public.rhythm_scores (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(player_name) between 2 and 16),
  song_id text not null check (char_length(song_id) between 2 and 80),
  difficulty text not null check (difficulty in ('easy', 'normal', 'hard')),
  score integer not null check (score between 0 and 10000000),
  accuracy numeric(7,4) not null check (accuracy between 0 and 100),
  max_combo integer not null check (max_combo between 0 and 10000),
  perfect_count integer not null check (perfect_count between 0 and 10000),
  great_count integer not null check (great_count between 0 and 10000),
  good_count integer not null check (good_count between 0 and 10000),
  miss_count integer not null check (miss_count between 0 and 10000),
  grade text not null check (grade in ('S', 'A', 'B', 'C', 'D')),
  created_at timestamptz not null default now()
);

create table if not exists public.rhythm_players (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(player_name) between 2 and 16),
  player_name_key text generated always as (lower(btrim(player_name))) stored,
  created_at timestamptz not null default now()
);

create unique index if not exists rhythm_players_name_key_idx
on public.rhythm_players (player_name_key);

-- 이미 점수를 가진 닉네임은 가장 오래된 표기를 기준으로 자동 등록합니다.
insert into public.rhythm_players (player_name)
select distinct on (lower(btrim(player_name))) player_name
from public.rhythm_scores
order by lower(btrim(player_name)), created_at asc, id asc
on conflict (player_name_key) do nothing;

alter table public.rhythm_scores enable row level security;
alter table public.rhythm_players enable row level security;

drop policy if exists "public leaderboard read" on public.rhythm_scores;
create policy "public leaderboard read"
on public.rhythm_scores
for select
to anon, authenticated
using (true);

drop policy if exists "public player names read" on public.rhythm_players;
create policy "public player names read"
on public.rhythm_players
for select
to anon, authenticated
using (true);

drop policy if exists "public player name claim" on public.rhythm_players;
create policy "public player name claim"
on public.rhythm_players
for insert
to anon, authenticated
with check (char_length(player_name) between 2 and 16);

drop policy if exists "public score insert" on public.rhythm_scores;
create policy "public score insert"
on public.rhythm_scores
for insert
to anon, authenticated
with check (
  char_length(player_name) between 2 and 16
  and exists (
    select 1
    from public.rhythm_players
    where player_name_key = lower(btrim(player_name))
  )
  and difficulty in ('easy', 'normal', 'hard')
  and score between 0 and 10000000
  and accuracy between 0 and 100
  and max_combo between 0 and 10000
  and perfect_count + great_count + good_count + miss_count between 1 and 10000
);

revoke all on table public.rhythm_scores from anon, authenticated;
grant select on table public.rhythm_scores to anon, authenticated;
grant insert (
  player_name, song_id, difficulty, score, accuracy, max_combo,
  perfect_count, great_count, good_count, miss_count, grade
) on table public.rhythm_scores to anon, authenticated;
grant usage, select on sequence public.rhythm_scores_id_seq to anon, authenticated;

revoke all on table public.rhythm_players from anon, authenticated;
grant select on table public.rhythm_players to anon, authenticated;
grant insert (player_name) on table public.rhythm_players to anon, authenticated;
grant usage, select on sequence public.rhythm_players_id_seq to anon, authenticated;

create index if not exists rhythm_scores_leaderboard_idx
on public.rhythm_scores (song_id, difficulty, score desc, accuracy desc, created_at asc);

drop view if exists public.rhythm_leaderboard_best;
create view public.rhythm_leaderboard_best
with (security_invoker = true)
as
select distinct on (lower(btrim(player_name)), song_id, difficulty)
  id,
  player_name,
  lower(btrim(player_name)) as player_name_key,
  song_id,
  difficulty,
  score,
  accuracy,
  max_combo,
  grade,
  created_at
from public.rhythm_scores
order by lower(btrim(player_name)), song_id, difficulty, score desc, accuracy desc, id asc;

grant select on public.rhythm_leaderboard_best to anon, authenticated;

-- 공개 브라우저 게임 특성상 완전한 계정 소유권이나 치팅 방지는 제공하지 않습니다.
-- 강한 본인 확인이 필요하면 Supabase Auth와 Edge Function을 함께 사용하세요.
