-- Supabase Dashboard → SQL Editor에서 이 파일 전체를 한 번 실행하세요.
-- 공개 브라우저 게임이므로 anon 역할에는 조회와 제한된 INSERT만 허용합니다.

create table if not exists public.rhythm_scores (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(player_name) between 2 and 16),
  song_id text not null check (char_length(song_id) between 2 and 80),
  difficulty text not null check (difficulty in ('easy', 'normal', 'hard')),
  score integer not null check (score between 0 and 10000000),
  accuracy numeric(7,4) not null check (accuracy between 0 and 100),
  max_combo integer not null check (max_combo between 0 and 10000),
  perfect_count integer not null check (perfect_count between 0 and 10000),
  great_count integer not null check (great_count between 0 and 10000),
  good_count integer not null check (good_count between 0 and 10000),
  miss_count integer not null check (miss_count between 0 and 10000),
  grade text not null check (grade in ('S', 'A', 'B', 'C', 'D')),
  created_at timestamptz not null default now()
);

alter table public.rhythm_scores enable row level security;

drop policy if exists "public leaderboard read" on public.rhythm_scores;
create policy "public leaderboard read"
on public.rhythm_scores
for select
to anon, authenticated
using (true);

drop policy if exists "public score insert" on public.rhythm_scores;
create policy "public score insert"
on public.rhythm_scores
for insert
to anon, authenticated
with check (
  char_length(player_name) between 2 and 16
  and difficulty in ('easy', 'normal', 'hard')
  and score between 0 and 10000000
  and accuracy between 0 and 100
  and max_combo between 0 and 10000
  and perfect_count + great_count + good_count + miss_count between 1 and 10000
);

revoke all on table public.rhythm_scores from anon, authenticated;
grant select on table public.rhythm_scores to anon, authenticated;
grant insert (
  player_name, song_id, difficulty, score, accuracy, max_combo,
  perfect_count, great_count, good_count, miss_count, grade
) on table public.rhythm_scores to anon, authenticated;
grant usage, select on sequence public.rhythm_scores_id_seq to anon, authenticated;

create index if not exists rhythm_scores_leaderboard_idx
on public.rhythm_scores (song_id, difficulty, score desc, accuracy desc, created_at asc);

-- 주의: 클라이언트 직접 등록 방식은 RLS와 제약조건으로 범위를 제한하지만
-- 완전한 치팅 방지는 아닙니다. 검증이 필요하면 Supabase Edge Function에서
-- 리플레이/채보 서명을 확인한 뒤 service_role로 INSERT하도록 확장하세요.
